Patch requested changes pr6
R2D2-2019/gas_detection pull request #8
Opened 2019-06-25 17:55 UTC by olivierverwoerd

changed to feedback from the pullrequest 6

2019-06-25 18:10 UTC, YouriMulder requested changes
I think the overall documentation is still pretty weak. I don't see any @param @return I think this might be an issue when creating a PR to master.

Your changes look fine. Please change the casts to static_casts. Using this instead of c style casts is recommended in the R2D2 project.

2019-06-25 18:10 UTC, YouriMulder commented on code/headers/gas_sensors_c.hpp
> +                        frame_gas.gas_id = uint8_t(gas.gas_id);
Here you cast the gas type to an uint8_t and in the operator<< for gas you cast it to an int. I think this is a bit inconsistent.

2019-06-25 18:10 UTC, YouriMulder commented on code/headers/gas_sensors_c.hpp
> +                        frame_gas.gas_id = uint8_t(gas.gas_id);
This is a c style case. You should use c++ static_cast

2019-06-25 18:10 UTC, YouriMulder commented on code/headers/gas_s.hpp
> +            return out << "gas_id: " << int(g.gas_id) << " value: " << g.value;
This is a c style cast. You should use static_cast.

2019-06-25 19:09 UTC, olivierverwoerd commented
The uint 16 is because the communucatie frame
The doxygen shouldnt be a problem since this is a patch brange

2019-06-26 08:34 UTC, YouriMulder approved these changes

2019-06-26 08:34 UTC, YouriMulder commented
> 
> 
> The uint 16 is because the communucatie frame
> The doxygen shouldnt be a problem since this is a patch brange

Ok then I understand why it is like this.

2019-06-26 08:45 UTC, merged